{% set python_min = "3.11" %}
{% set name = "hololinked" %}
{% set version = "0.3.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/hololinked-{{ version }}.tar.gz
  sha256: af4eb1fe2cc942b06465ccc50ed753d730f6b46e5cd4e965b916fa5d30e11406

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - argon2-cffi>=23.1.0
    - ifaddr>=0.2.0,<0.3
    - msgspec>=0.18.6
    - pyzmq>=25.1.0,<26.2
    - SQLAlchemy>2.0.21
    - SQLAlchemy_Utils>=0.41
    - pydantic>=2.8.0,<3.0.0
    - tornado>=6.3.3
    - jsonschema>=4.22.0,<5.0
    - httpx>=0.28.1,<29.0
    - sniffio>=1.3.1,<2.0
    - pymongo>=4.15.2
    - aiomqtt>=2.4.0

test:
  imports:
    - hololinked
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/VigneshVSV/hololinked
  summary: A ZMQ-based Object Oriented RPC tool-kit for instrument control/data acquisition or controlling generic python objects.
  license: BSD-3-Clause
  license_file: license.txt

extra:
  recipe-maintainers:
    - VigneshVSV
