{% set python_min = "3.11" %}
{% set name = "hololinked" %}
{% set version = "0.3.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/hololinked-{{ version }}.tar.gz
  sha256: 9ca8fa280707cc0898deece757e643795ca00f76e659fde6b5258687f5793622

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - argon2-cffi >=23.1.0
    - ifaddr >=0.2.0,<0.3
    - msgspec >=0.18.6
    - pyzmq >=25.1.0,<26.2
    - sqlalchemy >=2.0.21
    - sqlalchemy-utils >=0.41
    - pydantic >=2.8.0,<3.0.0
    - tornado >=6.3.3
    - jsonschema >=4.22.0,<5.0
    - httpx >=0.28.1,<29.0
    - sniffio >=1.3.1,<2.0
    - pymongo >=4.15.2
    - structlog >=25.5.0

test:
  imports:
    - hololinked
  commands:
    - pip install aiomqtt
    - python -c "import hololinked, aiomqtt; print('basic import ok')"
    - python -c "from hololinked.core import Thing, Property, action, Event; print('core submodule import ok')"
    - python -c "from hololinked.serializers import JSONSerializer, MsgpackSerializer; print('serializers submodule import ok')"
    - python -c "from hololinked.td import ThingModel; print('td submodule import ok')"
    - python -c "from hololinked.server.zmq import ZMQServer; print('server.zmq submodule import ok')"
    - python -c "from hololinked.server.http import HTTPServer; print('server.http submodule import ok')"
    - python -c "from hololinked.server.mqtt import MQTTPublisher; print('server.mqtt submodule import ok')"
    - python -c "from hololinked.client import ClientFactory, ObjectProxy; print('client submodule import ok')"
    - python -c "import hololinked.client.zmq; import hololinked.client.http; import hololinked.client.mqtt; print('client protocol submodules http,mqtt,zmq import ok')"
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/hololinked-dev/hololinked
  summary: A ZMQ-based protocol-agnostic object oriented RPC toolkit primarily focussed for instrumentation control, data acquisition or IoT
  license: Apache-2.0
  license_file: license.txt

extra:
  recipe-maintainers:
    - VigneshVSV
